# Hexo Configuration
# Site
title: Beginners Guide to Devops
subtitle: ''
description: ''
keywords: []
author: Kevin Lin & Sebastian Lopez
language: en
timezone: ''

# URL
url: https://<your-username>.github.io/<your-repo-name>  # Update with your GitHub username and repository name
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

# Writing
default_layout: post
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Theme
theme: landscape

# Deployment
deploy:
  type: git
  repo: https://github.com/kl63/is373_project.git
  branch: gh-pages
