name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Install Node.js and Hexo CLI
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install Hexo and dependencies
        run: |
          npm install hexo-cli -g
          npm install

      # Generate the static website
      - name: Generate Hexo site
        run: hexo generate

      # Clone the Playwright test repository
      - name: Clone Playwright test repository
        run: |
          git clone https://github.com/sebastianlop23/is375_plr.git
          cd is375_plr/tests
          npm install

      # Run the Playwright tests against the generated Hexo site
      - name: Run Playwright tests
        run: |
          cd is375_plr/tests
          npx playwright test --config=../playwright.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure deployment only happens if the tests pass
    if: github.event_name == 'push'

    steps:
      # Checkout the Hexo repository again (to prevent loss of state)
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Make sure it matches your environment

      # Install Hexo and dependencies
      - name: Install Hexo and dependencies
        run: |
          npm install hexo-cli -g
          npm install

      # Re-generate the static website (if necessary)
      - name: Generate Hexo site
        run: hexo generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo outputs the generated files to the 'public' directory

