name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master  # Deploy only when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v31
        with:
          node-version: '21'

      # Cache node_modules for faster builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      # Install Hexo and dependencies
      - name: Install dependencies
        run: npm install

      # Generate the Hexo static files
      - name: Build Hexo
        run: npm run generate

      # Disable Jekyll by creating a .nojekyll file
      - name: Disable Jekyll
        run: touch ./public/.nojekyll

      # Deploy the generated files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
