name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '21'
      HEXO_PORT: 4000  # Hexo server port

    steps:
      # Checkout the Hexo repository
      - name: Checkout Hexo Repository
        uses: actions/checkout@v3

      # Set up Node.js and install Hexo dependencies
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install Hexo and its dependencies
      - name: Install Hexo and Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      # Generate the Hexo site
      - name: Generate Hexo Site
        run: hexo generate

      # Clone the Playwright test repository
      - name: Clone Playwright Test Repository
        run: |
          git clone https://github.com/sebastianlop23/is375_plr.git
          cd is375_plr/tests
          npm install

      # Install required browsers for Playwright
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run Playwright tests
      - name: Execute Playwright Tests
        run: |
          cd is375_plr/tests
          npx playwright test --config=../playwright.config.js  # Adjust to point to your config file

      # Start the Hexo server persistently for testing
      - name: Start Hexo Server
        run: |
          nohup hexo server -p ${{ env.HEXO_PORT }} > hexo_server.log 2>&1 &
          sleep 5  # Give the server some time to start

      # Check if the Hexo server is running
      - name: Check Hexo Server
        run: |
          for i in {1..10}; do
            curl -I http://localhost:${{ env.HEXO_PORT }}/ && break
            echo "Waiting for Hexo server to be ready..."
            sleep 3
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure deployment only happens if the tests pass
    if: github.event_name == 'push'

    steps:
      # Checkout the Hexo repository again
      - name: Checkout Hexo Repository
        uses: actions/checkout@v3

      # Set Up Node.js environment for deployment
      - name: Set Up Node.js for Deployment
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Ensure consistency with the build environment

      # Install Hexo and dependencies for deployment
      - name: Install Hexo and Dependencies for Deployment
        run: |
          npm install -g hexo-cli
          npm install

      # Re-generate the static website for deployment
      - name: Regenerate Hexo Site
        run: hexo generate

      # Add .nojekyll file to disable Jekyll processing
      - name: Disable Jekyll
        run: touch ./public/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Ensure this matches your build output directory
