name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - master  # Use 'master' if that's your default branch
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hexo Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you want to use

      - name: Install Hexo and Dependencies
        run: |
          npm install -g hexo-cli
          npm install
          npx playwright install

      - name: Show Hexo Configuration
        run: cat _config.yml  # Log the Hexo configuration

      - name: Generate Hexo Site
        run: hexo generate

      - name: Start Hexo Server
        run: |
          nohup hexo server -p 4000 > hexo_server.log 2>&1 &
          sleep 5

      - name: Check if Hexo server is running
        run: |
          for i in {1..10}; do
            curl -I http://localhost:4000/ && break || echo "Waiting for Hexo server to be ready..." && sleep 3
          done
        shell: bash

      - name: Run Playwright Tests
        run: |
          npx playwright test --config=./playwright.config.js

      - name: Display Hexo server log (for debugging)
        if: failure()
        run: cat hexo_server.log

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout Hexo Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js for Deployment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you want to use

      - name: Install Hexo and Dependencies for Deployment
        run: |
          npm install -g hexo-cli
          npm install

      - name: Regenerate Hexo Site
        run: hexo generate

      - name: Add .nojekyll file
        run: touch ./public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
